# IRIS DATA SET CLASSIFICATION USING KNN

In [401]:
import pandas as pd
import numpy as np

In [402]:
from sklearn.datasets import load_iris

In [403]:
iris = load_iris()

In [404]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [405]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [406]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [407]:
pd.DataFrame(df).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [408]:
species = pd.DataFrame(iris.target_names)

In [409]:
species.columns = ['Class']

In [410]:
pd.DataFrame(species)

Class
0      setosa
1  versicolor
2   virginica

In [411]:
pd.DataFrame(df).head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [412]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [413]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [414]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [415]:
iris['data'].shape

(150, 4)

# Splitting Dataset

In [416]:
from sklearn.model_selection import train_test_split

In [417]:
X_train,X_test,y_train,y_test = train_test_split(iris['data'],iris['target'],random_state=0)

In [418]:
X_train.shape

(112, 4)

In [419]:
X_test.shape

(38, 4)

In [420]:
from sklearn.neighbors import KNeighborsClassifier

# Predicting Classes for 5 different data points

# K=1 

In [421]:
classifier =  KNeighborsClassifier(n_neighbors=1) #k=1

In [422]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [423]:
X_new = np.array([[5,3,1,0],[4.6,3.1,2,0.1],[7.2,3.1,5.1,1],[8,4,7,2]])

In [424]:
prediction = classifier.predict(X_new)

In [425]:
iris['target_names'][prediction]

array(['setosa', 'setosa', 'versicolor', 'virginica'], dtype='<U10')

In [426]:
classifier.score(X_test,y_test)

0.9736842105263158

# K=2

In [427]:
classifier =  KNeighborsClassifier(n_neighbors=2) #k=2

In [428]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [429]:
X_new = np.array([[5,3,1,0],[4.6,3.1,2,0.1],[7.2,3.1,5.1,1],[8,4,7,2]])

In [430]:
prediction = classifier.predict(X_new)

In [431]:
iris['target_names'][prediction]

array(['setosa', 'setosa', 'versicolor', 'virginica'], dtype='<U10')

In [432]:
classifier.score(X_test,y_test)

0.9736842105263158

# K=3

In [433]:
classifier =  KNeighborsClassifier(n_neighbors=3) #k=3

In [434]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [435]:
X_new = np.array([[5,3,1,0],[4.6,3.1,2,0.1],[7.2,3.1,5.1,1],[8,4,7,2]])

In [436]:
prediction = classifier.predict(X_new)

In [437]:
iris['target_names'][prediction]

array(['setosa', 'setosa', 'versicolor', 'virginica'], dtype='<U10')

In [438]:
classifier.score(X_test,y_test)

0.9736842105263158

# K=4

In [439]:
classifier =  KNeighborsClassifier(n_neighbors=4, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=10) #k=3

In [440]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_jobs=10, n_neighbors=4)

In [441]:
X_new = np.array([[5,3,1,0],[4.6,3.1,2,0.1],[7.2,3.1,5.1,1],[8,4,7,2]])

In [442]:
prediction = classifier.predict(X_new)

In [443]:
iris['target_names'][prediction]

array(['setosa', 'setosa', 'versicolor', 'virginica'], dtype='<U10')

In [444]:
classifier.score(X_test,y_test)

0.9736842105263158

# K=5

In [445]:
classifier =  KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski', metric_params=None, n_jobs=10) #k=3

In [446]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_jobs=10)

In [447]:
X_new = np.array([[5,3,1,0],[4.6,3.1,2,0.1],[7.2,3.1,5.1,1],[8,4,7,2]])

In [448]:
prediction = classifier.predict(X_new)

In [449]:
iris['target_names'][prediction]

array(['setosa', 'setosa', 'versicolor', 'virginica'], dtype='<U10')

In [450]:
classifier.score(X_test,y_test)

0.9736842105263158

# Performance Evaluation

In [451]:
classifier.score(X_test, y_test)

0.9736842105263158

In [452]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [453]:
y_pred = classifier.predict(X_test)
score = accuracy_score(y_test,y_pred)

In [454]:
print('Accuracy Score = ',score*100,'%')

Accuracy Score =  97.36842105263158 %


In [455]:
cm = confusion_matrix(y_pred, y_test)

In [456]:
print(cm)

[[13  0  0]
 [ 0 15  0]
 [ 0  1  9]]
